# Generated by Django 3.2.14 on 2022-08-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomBytes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ip', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('quota', models.IntegerField(default=1000)),
            ],
        ),
    ]
