# Generated by Django 3.2.14 on 2022-08-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_number', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_visit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='visit_num',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='randombytes',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
