# Generated by Django 3.2.14 on 2022-09-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_number', '0004_bufferindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randombytes',
            name='bytes',
            field=models.CharField(max_length=1048576),
        ),
    ]
