# Generated by Django 3.2.14 on 2022-09-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_number', '0005_alter_randombytes_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randombytes',
            name='bytes',
            field=models.BinaryField(max_length=1048576),
        ),
    ]
